name: secrets and deployment

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dist
        run: |
          mkdir -p dist
          echo "${{ github.sha }}" > dist/version.txt

      - name: Upload Artifact on Dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/develop' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    environment:
      name: staging
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
      
      - name: Show TOKEN length
        env:
          TOKEN: ${{ secrets.MY_API_TOKEN }}
        run: |
          echo "TOKEN length: ${#TOKEN}"
          echo "$TOKEN"

  deploy-production:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: production
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Deploy
        run: |
          echo "Deploying to production"